### ISSUE TITLE
Misleading Repo

### ISSUE THREAD

**Issue by Hypfer** [congatudo/congatudo-add-on#20]
While it's great that Valetudo is seeing use, I'm quite unhappy with this repo which appeared without me knowing and looks _exactly_ as if it was an official thing.

As this leads to a lot of confusion and therefore unhappy users, I'd like to ask you to 

- Stop using the Logo
- Stop using the name Valetudo as you do now
- Stop using a 90% copy-paste of the official readme
- Stop creating things that look like I've created them without asking or even telling me at all

Technically, this is a license violation but more importantly it's overall just a pretty bad thing to do.

Thank you

**Comment by txitxo0** [comment]
Hi!

We are working on a library to support Cecotec Conga robots by your incredible awesome Valetudo.

In the meanwhile, as we are using home assistant, we decided to create an addon in order to be able to add Valetudo to a home assistant server in a so easy way.

As we are working in the Cecotec Conga library, we decided to use this addon with the docker images from the fork where we are developing this library. This addon is thought to be able to use with others Docker images, so it is easy to use with the original repo too.

I guessed you already knew we were working on this library to support this other robots brand. I would like to remember that there is an issue or opened pr to be able to add this library into your repo.

We are always pointing to your repository, we think we should always refer to the original repo and his author.

Please, let us know if you still don't want us to use valetudo in the way we are doing right now

KR.

**Comment by Hypfer** [comment]
> In the meanwhile, as we are using home assistant, we decided to create an addon in order to be able to add Valetudo to a home assistant server in a so easy way.

Sure you can do that. You just can't call it Valetudo Add-On and use the Valetudo Logo.
You especially cannot copy paste the Logo and Readme to a Repo at all and also under a different license.

> I would like to remember that there is an issue or opened pr to be able to add this library into your repo.

Yeah an unfinished PR is definitely a valid reason to impersonate someone. /s

> We are always pointing to your repository, we think we should always refer to the original repo and his author.

And you should also not steal assets and impersonate people.

> Please, let us know if you still don't want us to use valetudo in the way we are doing right now

As I've said, please

- Stop using the Logo
- Stop using the name Valetudo as you do now
- Stop using a 90% copy-paste of the official readme
- Stop creating things that look like I've created them without asking or even telling me at all


Look, I really don't care about your project. Why would I open-source the code if I didn't want people to use it?
What I do however care about is making it look like it's an official thing.

I wouldn't have any issue with this project if it was called "Valetudo Conga Fork Community Add-On" because that's what its.
That's what sets expectations and that's what keeps your users from being my problem.

Also of course the whole readme copy-paste thing needs to go
